Repository tenstorrent/tt-zephyr-platforms, pull requests merged in 2025-07, with the labels that each got.

#375 zephyr: patches: remove unused DT_INST_IRQN_BY_NAME patch
  zephyr/patches.yml
  zephyr/patches/zephyr/include-zephyr-devicetree-add-DT_INST_IRQN_BY_NAME.patch
Labels: ci ♾️, zephyr 🪁, patches 🩹

#382 ci: release: populate boards in prepare-release job
  .github/workflows/release.yml
Labels: ci ♾️, hotfix🔥🚒🧑‍🚒, release ✅

#383 ci: release: quote output of jq
  .github/workflows/release.yml
Labels: ci ♾️, hotfix🔥🚒🧑‍🚒, release ✅

#384 ci: release: embed quotes in quotes so output of jq is quoted
  .github/workflows/release.yml
Labels: ci ♾️, hotfix🔥🚒🧑‍🚒, release ✅

#392 ci: bump tt-flash rev to 3.3.5, tt-smi rev to 3.0.23
  .github/workflows/hardware-long.yml
  .github/workflows/hardware-smoke.yml
  scripts/requirements.txt
Labels: ci ♾️, tt-flash 📸, tt-smi 🎮, python 🐍

#376 ci: add a stale bot to clean up inactive PRs and issues
  .github/workflows/stale_issue.yml
Labels: ci ♾️

#396 scripts: build-combined-fwbundle: remove stale comment
  scripts/build-combined-fwbundle.sh
Labels: scripts 📜

#412 tenstorrent/tt-metal#24359: Update to latest container and use new system of calling tests
  .github/workflows/hardware-smoke.yml
Labels: ci ♾️

#424 MAINTAINERS: add danieldegrasse to release team
  MAINTAINERS.yml
Labels: area: Process

#426 readme: additional fixes for readme based on user feedback
  README.md
Labels: Documentation 📄

#431 readme: remove convenience variables, make a separate test section
  README.md
Labels: Documentation 📄

#438 readme: install packages before fetching blobs
  README.md
Labels: Documentation 📄

#447 license: move non-apache licensing details to readme
  LICENSE
  LICENSE_understanding.txt
  README.md
Labels: area: Process, license 🪪

#453 ci: do not retry if twister jobs fail
  .github/workflows/hardware-long.yml
  .github/workflows/hardware-smoke.yml
  .github/workflows/run-unit-tests.yml
Labels: ci ♾️
